#+title: Innovation Lab EFREI Paris
* Fonctionnement
L'Innovation Lab est un tiers lieu au sein de l'école permettant aux étudiants de réaliser leur projet.
Ce lieu se divise en deux parties. La première se situe à gauche en rentrant par la porte centrale, c'est un espace de travail en libre accès.
La deuxième partie est un espace de fabrication dont l'accès est reglementé, car on y retrouve les machines et les espaces de stockages. Pour accéder à ce lieu, voici les éléments à savoir:
L'Innovation Lab est principalement géré par le Fablab Manager remi.griot@efrei.fr. Il cogère le lieu avec des étudiants, les étudiants encadrants.
Gérer le lieu signifie l'organisier, le maintenir, acceuillir les utilisateurs, les former...
En général, le lieu sera ouvert aux utilsisateurs durant les permanences, dont l'agenda est ci dessous.
Pour utiliser les machines, il faudra suivre une formation et obtenir un open badge. Tout est décrit ci dessous.

* Agenda
Permanences, évenements, formations... tout est ici:
#+begin_export html
<iframe src="https://calendar.google.com/calendar/embed?src=rd05kdhplh71pcovlkmacd392c%40group.calendar.google.com&ctz=Europe%2FParis" style="border: 0" width="800" height="600" frameborder="0" scrolling="no"></iframe>
#+end_export

* Liste des étudiants encadrants
Les étudiants encadrants sont des étudiants qui co-gèrent l'Innovation Lab.
Ils sont responsables de la bonne marche du lieu.

- Le Callonec	Baptise	L1	baptiste.le-callonnec@efrei.net
- Calle	Illian	L1	illian.calle@efrei.net
- Chazard	Elisa	L2	elisa.chazard@efrei.net
- Guez	Victoria	L2	victoria.guez@efrei.net
- Al Khoury	Layla	L2	layla.al.khoury.aoun@efrei.net
- Alba Sanchez	Luis	L2	luis.alba.sanchez@efrei.net
- Darbellay	Martin	L2	martin.darbellay@efrei.net
- Lucas	Martin	L2	martin.lucas@efrei.net
- Morel	Nathan	L2	nathan.morel@efrei.net
- Vialle	Martin	L2	martin.vialle@efrei.net
- Vincent	Esteban	L2	esteban.vincent@efrei.net
- Dheilly	Robin	L3	robin.dheilly@efrei.net
- Guillot	Sasha	l3	sasha.guillot@efrei.net
- Zhou	Killian	L3	killian.zhou@efrei.net
- Babin	Victor	L3	victor.babin@efrei.net
- Dewatre	Pierre	L3	pierre.dewatre@efrei.net
- Geslot	Gaspard	L3	gaspard.geslot@efrei.net
- Howayek	Elie	L3	elie.howayek@efrei.net
- Iloo	Moise	L3	moise.iloo.liandja@efrei.net
- Lefevre	Valentin	L3	valentin.lefevre@efrei.net
- Stasik	Victoria	L3	victoria.stasik@efrei.net
- Wang	Justine	L3	justine.wang@efrei.net
- Collin	Alexis	M1	alexis.collin@efrei.net
- Cotton	Florent	M1	florent.cotton@efrei.net
- Mauvezin	Charlotte	M1	charlotte.mauvezin@efrei.net
- Phonchareun	Alex	M1	alex.phonchareun@efrei.net
- Tazi	Kenza	M1	kenza.tazi@efrei.net
- Yann Kader	Obou N Do	M1	yann.kader.axel.obou.n.do@efrei.net
- Angebaud      Calixte		M1	calixte.angebaud@efrei.net


* Equipements
** Impression 3D
** Découpe Laser
** Fraiseuse Numérique
** Espace electronique
** Espace de réalité virtuelle
** Outillage
* Formations
Impression 3D, Scanner 3D, découpe laser, électronique… Pensez à préciser la formation qui
vous intéresse lors de la prise de rendez-vous. Si vous êtes indécis, l’impression 3D est
certainement un bon début.
* Reglement intérieur
[[./doc/RI InnovationLab V3.pdf]]
* Réseau Sociaux
[[https://www.instagram.com/innovationlab_efrei/]]

* Projets

#+begin_export html

<iframe src="https://view.monday.com/embed/2048659497-cb5faeaa79a56795cecfec114cc7b2f4?r=use1" width=800 height=600 style="border: 0; box-shadow: 5px 5px 56px 0px rgba(0,0,0,0.25);"></iframe>

#+end_export

* FAQ

*Dois-je payer quelque chose ?* \\
Non, l’accès à l’Innovation Lab est gratuit.

*Que fait-on à l’Innovation Lab ? Puis je y mener des projets personnels ?* \\
Oui, tous les projets sont les bienvenus : Entrepreneurial, personnel, associatif, académique…
Cependant, ces projets doivent être renseignés via une fiche projet. Cette fiche est courte et simple à remplir. 

*Dois-je fournir mes bobines de filament pour imprimer en 3D?* \\
Les bobines pour l’impression 3D sont fournies, les utilisateurs
n’ont pas à apporter de filament. Les changements de bobines et
la maintenance des machines sont sous la responsabilité des
étudiants encadrants.\\

*Dois-je fournir le consommable pour la découpe laser?* \\
Oui, mais il est possible que vous trouviez votre bonheur dans les
chutes mises gratuitement à la disposition de tous. \\

*… et si j’ai besoin de plus de consommable ?* \\
Pour les grandes découpes, c’est à vous de fournir le
consommable. Si vous le laissez sur place, il faudra
impérativement l’étiqueter avec la date et un e-mail. A noter
qu’un état des lieux en fin de semestre rebascule tout le
consommable dans le pot commun. Le stockage est limité dans le
temps. \\

*Puis je laisser du matériel ?* \\
Du stockage est mis à disposition le temps d’un semestre. Vous pouvez utiliser les casiers gris en y
mettant votre nom et la date. Les casiers seront vidés lors de l’état des lieux de fin de semestre. \\

*L’Innovation Lab est ouvert le samedi ?* \\
Si vous êtes étudiant encadrant, vous pouvez utiliser le lieu quand vous le souhaitez, sous réserve que
le campus soit ouvert. En tant qu’utilisateurs, vous pouvez seulement venir durant les permanences. \\

*Comment devenir étudiant encadrant ?* \\
Lorsque vous êtes étudiants encadrants, vous bénéficiez d’un accès privilégié à l’Innovation Lab, sous
réserve que vous soyez disponibles pour une permanence hebdomadaire. Vous pouvez déjà vous
familiariser avec le lieu en tant qu’utilisateur et passer quelques formations puis devenir encadrants
en envoyant votre demande à remi.griot@efrei.fr \\
