#+title: Presentations projets
#+description: Presentations projets 
#+author: remi.griot@efrei.fr
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup
#+OPTIONS: toc:nil num:nil


* Tous les _vendredi de 11h30 à 12h_ à l'Innovation Lab

*Qui fait quoi?!*\\
L'idée est de créer un moment d'échange autour des différents projets et d'y méler étudiants et enseignants.
Des présentations techniques et informelles qui seront l'occasion pour les presentateurs de partager l'avancement de leur travaux et d'aiguiser leur discours!\\
/15 minutes de présentation / 15 minutes d'échange. \\
A midi vous êtes dehors, promis!/



**  20/01 -  Robminton - /projet M2/
Robots ramasseur & lanceur de volants de badminton
**  24/01 - Course de voiture autonome - /projet M2/
Conception d'une voiture à l'echelle 1/10e en vue de participer à une course de voiture autonome.
**  03/02 - Localisation Roller - /projet M2/
Localiser les sportifs lors de compétition de roller
**  10/02 - Bras robotisé (TBC) - /projet M2/
**  17/02 - DoRobo - /projet M2/
"DoRobo" est un robot mobile autonome chargé de réaliser la prise de mesure de qualité de l'air ambiant pour la prévention de risques liés à la fuite de produits toxiques dans les entrepôts de stockages et autres lieux utilisant ou entreposant de nombreux produits nocifs pour l'homme.
**  24/02 - ?
**  03/03 - Reconnaissance des émotions - /projet M2/
Construction d’une base de données labelisée, étude statistique des caractéristiques de la voix et reconnaissance automatique d’émotions
