#+title: Reparateur
#+description: Fonctionnement de l'Innovation Lab
#+author: remi.griot@efrei.fr
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup
#+OPTIONS: toc:nil num:nil

** Déroulé de l'evenement

Les personnes sont acceuillies à l'entrée du repair café par un organisateur
qui va vérifier les inscriptions puis les diriger vers les réparateurs.
En tant que réparateur, vous avez juste à attendre derrière votre paillase.
On se donne 40 minutes maximum par objet, et la consigne a été donner d'amener un objet par personne.

** Avant la réparation

Les "Repair café" sont des moments d'échanges et de convivialité. L'acceuil que vous faites à la personne qui apporte un objet est primordial.
N'oubliez pas que la réparation se fait en collaboration avec elle. Vous pouvez obtenir quelques précieux renseignements avant de vous lancer, ce qui augmente les chances de réparations et peut permettre 
de mettre la personne plus à l'aise.
- L'objet a t il beaucoup servi ?
- A qui appartient-il ?
- La personne a t elle un attachement particulier à cet objet ?
- La personne a t elle chercher à le réparer elle même ? Sinon pourquoi?
- Selon le type d'objet, vous pouvez installer un dialogue et échanger avec la personne sur ses habitudes, ses gouts....
Par exemple, j'ai le souvenir d'une personne agée dont le magnetoscope était en panne. Elle était trés attachée à sa collection de film en cassette. 
J'ai pu sortir la cassette qui était coincée à l'interieur mais pas pu le réparer.
Nous avons ensuite chercher ensemble sur le Bon Coin des magnétoscopes bon marchés et pas loin de son domicile.

L'issue du moment que vous passez avec la personne n'est pas certaine. Nous souhaitons tous que ça soit un réparation, mais ça peut être un nouvel achat, 
la commande d'une pièce de rechange, la prise de RDV pour un autre repair café...

** Pendant la réparation

La réparation se fait à deux. Si certaines opérations peuvent être faites par la personne, n'hésitez pas à lui demander si elle veut les faire.
A noter que réparer un objet peut se faire en plusieurs fois. La session s'arretera peut être au diagnostique de panne ou à la commande d'une pièce de rechange.
Si vous le souhaitez, vous pouvez donner RDV à la personne pour continuer la réparation, dans le cadre d'un futur repair café ou pas.

** Quelques conseils

+ Avant de démonter, regarder sur internet si la panne est connue
+ Démonter l'objet hors secteur
+ Lors du démontage de l'objet, prendre des photos qui aideront au remontage. Classer les visses dans l'ordre du démontage...
+ Une fois démonter, vous pouvez vérifier la présence de tension avec un multimètre (il peut y avoir une batterie ou des condensateurs encore chargés)
+ Remettre en tension une fois l'objet remonté. Si votre réparation a crée un court circuit, il peut y avoir des projections.
+ Si vous êtes amener à faire des soudures, porter des lunettes de protection. Même chose pour la personne qui apporte l'objet.
+ Demander conseils aux autres réparateurs si vous n'êtes pas sûr.


** Liens utiles


https://fr.ifixit.com/

https://solar.lowtechmagazine.com/fr/2021/10/how-to-build-a-low-tech-solar-panel.html

https://wiki.lowtechlab.org/wiki/Group:Low-tech_Lab
