
* Réparateur

** Avant la réparation

Les repair café sont des moments d'échanges, et l'acceuil que vous faites à la personne qui apporte un objet est primordial.
N'oubliez pas que la réparation se fait avec elle. Vous pouvez obtenir quelques renseignements précieux avant de vous lancer dans la réparation.
- L'objet a t il beaucoup servi ?
- A qui appartient-il ?
- La personne a t elle un attachement particulier à cet objet ?
- La personne a t elle chercher à le réparer elle même ? Sinon pourquoi?
- Selon le type d'objet, vous pouvez installer un dialogue et échanger avec la personne sur ses habitudes, ses gouts....
Par exemple, j'ai le souvenir d'une personne agée dont le magnetoscope était en panne. Elle était très attachée à sa collection de film en cassette. J'ai pu sortir la cassette qui était coincée à l'interieur mais pas pu le réparer.
Nous avons ensuite chercher ensemble sur le bon coin des magnétoscopes bon marché et pas loin de son domicile.

L'issue de la réparation n'est pas certaine. Un nouvel achat, la commande d'une pièce de rechange...

** Avant la réparation

La réparation se fait à deux. Si certaines opérations peuvent être faites par la personne, n'heistez pas à lui demander si elle veut les faire.



https://fr.ifixit.com/

https://solar.lowtechmagazine.com/fr/2021/10/how-to-build-a-low-tech-solar-panel.html
